development:
  adapter: mysql
  encoding: utf8
  database: running_status
  pool: 5
  username: root
  password: root 

test:
  adapter: mysql
  encoding: utf8
  database: running_status_test
  pool: 5
  username: root
  password: root 


production:
  adapter: mysql
  encoding: utf8
  database: voyagest_status
  pool: 5
  username: voyagest_root
  password: hoppers123
  port: 3306

