development:
  adapter: mysql2
  encoding: utf8
  database: running_status
  pool: 5
  username: root
  password: root 

test:
  adapter: mysql2
  encoding: utf8
  database: running_status_test
  pool: 5
  username: root
  password: root 


production:
  adapter: mysql2
  encoding: utf8
  database: running_status
  pool: 5
  username: root
  password: root 
